### ISSUE TITLE
互换友链

### ISSUE THREAD

**Issue by Elykia093** [canyie/canyie.github.io#10]
- name: Elykia
  link: https://blog.elykia.cn/
  avatar: https://bu.dusays.com/2024/10/25/671b2438203a6.gif
  descr: 致以无暇之人
  siteshot: https://bu.dusays.com/2024/10/25/671b50dc2dd2b.png
标签 #Android #摸鱼
明天中午会加上您的友链

**Comment by canyie** [comment]
感谢申请，明天更新博客的时候会加上
