### ISSUE TITLE
交换友链~

### ISSUE THREAD

**Issue by w568w** [canyie/canyie.github.io#2]
- Blog: 行云小站
- 地址: https://w568w.eu.org/
- 头像: ![](https://cn.gravatar.com/avatar/a07da489e1f63eaa83cded683786df23?d=mm&s=200)  

- 头像链接 :https://cn.gravatar.com/avatar/a07da489e1f63eaa83cded683786df23?d=mm&s=200  

- 标签: `#Android` `#摸鱼`

稍后会[在这里](https://w568w.eu.org/gays.html)加上您的友链~ :smile_cat:

**Comment by canyie** [comment]
估计要等到国庆，我现在在学校没电脑没法改

**Comment by w568w** [comment]
哈哈，没关系，我已经加上友链了: https://w568w.eu.org/gays.html   
  
话说高中生就会写ART Injection真的很强啊 😸 我高中时是个废柴了ww

**Comment by canyie** [comment]
已添加友链
另外我是中职生（初中的时候没认真学emm，现在必须认真了没什么时间搞项目了），lody才是真大佬，高中写了Legend, VirtualApp等等，我只能仰望啊啊啊
