### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by dabao1955** [canyie/canyie.github.io#6]
您好大佬，站点最近还开放友链申请吗？

**Comment by canyie** [comment]
接受呀，需要有名称、头像链接、和至少一个标签哦~

**Comment by dabao1955** [comment]
> 接受呀，需要有名称、头像链接、和至少一个标签哦~

感谢大佬回复我这个小白www

名称： dpkg123的博客
头像： https://dpkg123.site/favicon.jpg
网址： https://dpkg123.site/
标签： Android

**Comment by canyie** [comment]
已经添加了哦~
