### ISSUE TITLE
link

### ISSUE THREAD

**Issue by df13954** [canyie/canyie.github.io#7]
- name: 黄大官AOSP
      link: https://df13954.github.io/
      avatar: https://github.com/df13954/df13954.github.io/blob/main/img/avatar.jpeg
      descr: Android

**Comment by canyie** [comment]
已添加。另外提醒一下：你的博客点击 Follow me 跳转到的不是你的 github，是一个叫 xxxxxx 的用户，是否是配置错误？

**Comment by df13954** [comment]
> 已添加。另外提醒一下：你的博客点击 Follow me 跳转到的不是你的 github，是一个叫 xxxxxx 的用户，是否是配置错误？

3q,忘记配置了下次更新
