### ISSUE TITLE
我呢我的友情链接呢

### ISSUE THREAD

**Issue by NgaiYeanCoi** [canyie/canyie.github.io#8]
NgaiYeanCoi
头像链接：https://blog.nyc1.xyz/image/icon.jpg
#NYC

**Comment by NgaiYeanCoi** [comment]
link:https://blog.nyc1.xyz/

**Comment by canyie** [comment]
你那个博客里都没我的友链哎

**Comment by NgaiYeanCoi** [comment]
> 你那个博客里都没我的友链哎

我到时再加宝贝

**Comment by canyie** [comment]
背景卡片用什么颜色，搞个灰色？

**Comment by NgaiYeanCoi** [comment]
> 背景卡片用什么颜色，搞个灰色？

可以hhhhh

**Comment by canyie** [comment]
好啦好啦搞完了

**Comment by NgaiYeanCoi** [comment]
> 好啦好啦搞完了

谢谢大佬
